<a href="https://colab.research.google.com/github/ayushsaxena90/MLCourseShef/blob/main/KNN_Classification_Ayush.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

#Now we are going to use the sklearn library to load the dataset - iris.csv

In [4]:
from sklearn.datasets import load_iris
data1 = load_iris()
data1

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

#Input Data:

In [5]:
X = pd.DataFrame(data1['data'], columns = data1['feature_names'])
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [7]:
#Output Columns
y = pd.DataFrame(data1['target'], columns = ['target_names'])
y

target_names
0               0
1               0
2               0
3               0
4               0
..            ...
145             2
146             2
147             2
148             2
149             2

[150 rows x 1 columns]

In [8]:
print(X.shape)
print(y.shape)

(150, 4)
(150, 1)


Since the data values are not very far from each other hence we can skip the standardscaler process

#Train Test Splitting

In [10]:
from sklearn.model_selection import train_test_split

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.75, random_state = 0)

In [52]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(112, 4)
(38, 4)
(112, 1)
(38, 1)


In [53]:
#Loading the KNN ML Model
from sklearn.neighbors import KNeighborsClassifier
model1 = KNeighborsClassifier()   # Here the default value of k is 5. If you want different value, then specify in the parenthesis

In [54]:
#Training the Model
model1.fit(X_train, y_train)

KNeighborsClassifier()

In [55]:
#Predict
y_pred = model1.predict(X_test)
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2])

In [56]:
#Actual results
y_test

target_names
114             2
62              1
33              0
107             2
7               0
100             2
40              0
86              1
76              1
71              1
134             2
51              1
73              1
54              1
63              1
37              0
78              1
90              1
45              0
16              0
121             2
66              1
24              0
8               0
126             2
22              0
44              0
97              1
93              1
26              0
137             2
84              1
27              0
127             2
132             2
59              1
18              0
83              1

In [57]:
# Model Evaluation
from sklearn.metrics import accuracy_score

In [58]:
print(accuracy_score(y_test, y_pred))

0.9736842105263158


In [59]:
#Checking Log Loss
from sklearn.metrics import log_loss

In [60]:
y_pred_proba = model1.predict_proba(X_test)
y_pred_proba

array([[0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0.6, 0.4],
       [1. , 0. , 0. ],
       [0. , 0.8, 0.2],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0.2, 0.8],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0.2, 0.8],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ]])

In [61]:
print(log_loss(y_pred, y_pred_proba))

0.031059375729174405


#Confusion Metrix

In [49]:
from sklearn.metrics import confusion_matrix

In [63]:
print(confusion_matrix(y_test, y_pred))

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
